=== AsafEZ/Java-Guess-Market-2026/Engine/src/main/resources/GM-EX3-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="description" type="xs:string"/>
    <xs:element name="commission">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:int">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="on-close"/>
                                <xs:enumeration value="on-purchase"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="b" type="xs:int"/>
    <xs:element name="Guess-Market">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-events"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-order-book">
        <xs:complexType>
            <xs:attribute name="initial" type="xs:int" use="required"/>
            <xs:attribute name="d" type="xs:int" use="required"/>
            <xs:attribute name="allow-mint" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="false"/>
                        <xs:enumeration value="true"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-options">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-option" maxOccurs="2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-option" type="xs:string"/>
    <xs:element name="GM-method">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="GM-LMSR"/>
                <xs:element ref="GM-order-book"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-events">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-event" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element ref="commission"/>
                <xs:element ref="GM-options"/>
                <xs:element ref="GM-method"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GM-LMSR">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="b"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AsafEZ/Java-Guess-Market-2026/Engine/src/test/resources/assignment3/xml/multiple.xml
<?xml version="1.0" encoding="UTF-8"?>
<Guess-Market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX3-Schema.xsd">
    <GM-events>
        <GM-event name="Earth Quake on Dead Sea">
            <description>Will there be an earth quake on the dead sea until the December 31th 2026</description>
            <commission type="on-purchase">50</commission>
            <GM-options><GM-option>Yes</GM-option><GM-option>No</GM-option></GM-options>
            <GM-method><GM-order-book allow-mint="false" initial="1000" d="1"/></GM-method>
        </GM-event>
        <GM-event name="World Cap Winner">
            <description>Who do you think will win the world cap ?</description>
            <commission type="on-close">15</commission>
            <GM-options><GM-option>Argentina</GM-option><GM-option>Spain</GM-option></GM-options>
            <GM-method><GM-order-book allow-mint="true" initial="100" d="1"/></GM-method>
        </GM-event>
        <GM-event name="Will it rain tomorrow ?">
            <description>Will there be 30 mm of rain tomorrow at Alenbi 283 st by 12:00 PM ?</description>
            <commission type="on-close">10</commission>
            <GM-options><GM-option>Yes</GM-option><GM-option>No</GM-option></GM-options>
            <GM-method><GM-LMSR><b>200</b></GM-LMSR></GM-method>
        </GM-event>
    </GM-events>
</Guess-Market>

=== AsafEZ/Java-Guess-Market-2026/Engine/src/test/resources/assignment3/xml/small.xml
<?xml version="1.0" encoding="UTF-8"?>
<Guess-Market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX3-Schema.xsd">
    <GM-events>
        <GM-event name="Mujtaba is Dead">
            <description>This event gambles if Mujtaba is a live or not. it will be determined if he will be shown in public until 31.8.26</description>
            <commission type="on-purchase">5</commission>
            <GM-options>
                <GM-option>Hell Yea !</GM-option>
                <GM-option>No way !</GM-option>
            </GM-options>
            <GM-method><GM-LMSR><b>100</b></GM-LMSR></GM-method>
        </GM-event>
    </GM-events>
</Guess-Market>
